//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusDetails.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BusManagementDBContext : DbContext
    {
        public BusManagementDBContext()
            : base("name=BusManagementDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BusInfo> BusInfoes { get; set; }
    
        public virtual int spInsertBusInfo(string boardingPoint, Nullable<System.DateTime> travelDate, Nullable<decimal> amount, Nullable<int> rating)
        {
            var boardingPointParameter = boardingPoint != null ?
                new ObjectParameter("BoardingPoint", boardingPoint) :
                new ObjectParameter("BoardingPoint", typeof(string));
    
            var travelDateParameter = travelDate.HasValue ?
                new ObjectParameter("TravelDate", travelDate) :
                new ObjectParameter("TravelDate", typeof(System.DateTime));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("Amount", amount) :
                new ObjectParameter("Amount", typeof(decimal));
    
            var ratingParameter = rating.HasValue ?
                new ObjectParameter("Rating", rating) :
                new ObjectParameter("Rating", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertBusInfo", boardingPointParameter, travelDateParameter, amountParameter, ratingParameter);
        }
    }
}
